// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/martinusiron/PayFlow/internal/auditlog/domain"
	mock "github.com/stretchr/testify/mock"
)

// AuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type AuditLogRepository struct {
	mock.Mock
}

// LogAction provides a mock function with given fields: ctx, log
func (_m *AuditLogRepository) LogAction(ctx context.Context, log domain.AuditLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for LogAction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditLogRepository creates a new instance of AuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogRepository {
	mock := &AuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
