// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/martinusiron/PayFlow/internal/overtime/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// OvertimeRepository is an autogenerated mock type for the OvertimeRepository type
type OvertimeRepository struct {
	mock.Mock
}

// GetOvertimeByUser provides a mock function with given fields: ctx, userID, start, end
func (_m *OvertimeRepository) GetOvertimeByUser(ctx context.Context, userID int, start time.Time, end time.Time) ([]domain.Overtime, error) {
	ret := _m.Called(ctx, userID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetOvertimeByUser")
	}

	var r0 []domain.Overtime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) ([]domain.Overtime, error)); ok {
		return rf(ctx, userID, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, time.Time, time.Time) []domain.Overtime); ok {
		r0 = rf(ctx, userID, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Overtime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitOvertime provides a mock function with given fields: ctx, ot
func (_m *OvertimeRepository) SubmitOvertime(ctx context.Context, ot domain.Overtime) (int, error) {
	ret := _m.Called(ctx, ot)

	if len(ret) == 0 {
		panic("no return value specified for SubmitOvertime")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Overtime) (int, error)); ok {
		return rf(ctx, ot)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Overtime) int); ok {
		r0 = rf(ctx, ot)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Overtime) error); ok {
		r1 = rf(ctx, ot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOvertimeRepository creates a new instance of OvertimeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOvertimeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OvertimeRepository {
	mock := &OvertimeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
